### ISSUE TITLE
Cease and Desist – Unauthorized Use of the Name "Alpis"

### ISSUE THREAD

**Issue by klodr** [turkaysoftware/alpis#1]
Dear Eray Türkay,

We are writing to bring to your attention a matter of serious concern regarding the unauthorized use of the name "Alpis" by your application.

Our company, Alpis, has been operating under this name for over 10 years. The name "Alpis" is not only central to our brand identity but is also legally protected as part of our intellectual property. We have built a strong reputation and recognition in the market, which is now being compromised by the use of this name by your application.

The use of "Alpis" by your application creates confusion among our customers and dilutes the distinctiveness of our brand, which we have worked hard to establish over the years. It also constitutes an infringement on our rights, as we have rights to the name under applicable intellectual property laws.

We hereby demand that you immediately cease and desist from using the name "Alpis" for your application or any related services, and that you provide written confirmation of your compliance within 15 days of receiving this message. Failure to do so will leave us no choice but to pursue all legal remedies available to us, including but not limited to filing a lawsuit for trademark infringement, seeking damages, and requesting injunctive relief.

We trust that this matter can be resolved amicably and without the need for further legal action. We await your prompt response and action on this matter.

Yours sincerely,
Claude Perrin
CEO 
Alpis
13 Bis avenue de la Motte Picquet
75007 Paris

**Comment by turkaysoftware** [comment]
> Dear Eray Türkay,
> 
> We are writing to bring to your attention a matter of serious concern regarding the unauthorized use of the name "Alpis" by your application.
> 
> Our company, Alpis, has been operating under this name for over 10 years. The name "Alpis" is not only central to our brand identity but is also legally protected as part of our intellectual property. We have built a strong reputation and recognition in the market, which is now being compromised by the use of this name by your application.
> 
> The use of "Alpis" by your application creates confusion among our customers and dilutes the distinctiveness of our brand, which we have worked hard to establish over the years. It also constitutes an infringement on our rights, as we have rights to the name under applicable intellectual property laws.
> 
> We hereby demand that you immediately cease and desist from using the name "Alpis" for your application or any related services, and that you provide written confirmation of your compliance within 15 days of receiving this message. Failure to do so will leave us no choice but to pursue all legal remedies available to us, including but not limited to filing a lawsuit for trademark infringement, seeking damages, and requesting injunctive relief.
> 
> We trust that this matter can be resolved amicably and without the need for further legal action. We await your prompt response and action on this matter.
> 
> Yours sincerely, Claude Perrin CEO Alpis 13 Bis avenue de la Motte Picquet 75007 Paris

Okay, I'm scrapping a project I've been developing for months. I'll call it something else.
